spec:
  replicas: 1
  revisionHistoryLimit: 2
  
  template:
    spec:
      serviceAccountName: sa-kameel-amq
      containers:
        -
          resources:
            requests:
              cpu: "0.2"
              memory: 128Mi
            limits:
              cpu: "1.0"
              memory: 512Mi
          env:
          - name: AMQP_SERVICE_NAME
            value: broker-amq-amqp.djiminjus.svc
          - name: AMQP_USERNAME
            value: admin
          - name: AMQP_PASSWORD
            value: password
          - name: AMQP_PARAMETERS
            value: transport.trustAll=true&transport.verifyHost=false&amqp.idleTimeout=120000
          - name: JAVA_OPTIONS
            value: -Dfabric8.config.plugin.enabled=true
